### ISSUE TITLE
Woodcutter Variants don't drop when broken

### ISSUE THREAD

**Issue by TheMasterBlaster** [pnk2u/More-Nemos-Woodcutter-Variants#1]
Seems none of the Woodcutter variants drop when broken. All mods are updated to the latest versions for 1.21. Tested on Server as well as Singleplayer

**Comment by pnk2u** [comment]
Thank you so much for reporting this, fix will be out in a few hours. I'll post another comment when it is.

**Comment by pnk2u** [comment]
Okay, version 1.1.0 is out and hopefully fixes this issue.
