### ISSUE TITLE
[Mod Compat] Not compatible with Better Clouds

### ISSUE THREAD

**Issue by heide-oficial** [pnk2u/More-Nemos-Woodcutter-Variants#2]
Nemo's More Woodcutter Variants isn't compatible with Better Clouds, it crashes at Minecraft startup.

OS: Windows 11 Pro
GPU: RX 5500 XT
Minecraft: 1.21
Mod version: 1.1.1
Mod Loader: Fabric 0.16.9
Crash log: [crash.txt](https://github.com/user-attachments/files/17678781/crash.txt)
Better Clouds issue thread: https://github.com/Qendolin/better-clouds/issues/160

**Comment by pnk2u** [comment]
First of all: Thanks for finding and reporting this problem. I also appreciate you linking the issues. (:
Secondly: Sorry about that, as mentioned by the Better Clouds dev, this is solely on me. Will fix and upload the fixed version in about 3-4h and comment here again once that has happened.

**Comment by pnk2u** [comment]
Thank you for your patience, the fixed version (1.1.2) has been uploaded. (:
